# Generated by Django 4.0.4 on 2022-05-09 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default=None, max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='그룹 초대 코드'),
        ),
    ]
