# Generated by Django 4.0.4 on 2022-05-03 07:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiontag',
            options={'verbose_name': '권한 태그', 'verbose_name_plural': '권한 태그 목록'},
        ),
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default=None, max_length=5, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='그룹 초대 코드'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='그룹 공개 여부'),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 일시')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrived_join_requests', to='users.group', verbose_name='대상 그룹')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청 유저')),
            ],
            options={
                'verbose_name': '그룹 가입 요청',
                'verbose_name_plural': '그룹 가입 요청 목록',
            },
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='single join request'),
        ),
    ]
