# Generated by Django 4.0.4 on 2022-05-09 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_group_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(db_index=True, related_name='groups', to=settings.AUTH_USER_MODEL, verbose_name='멤버 목록'),
        ),
    ]
