# Generated by Django 4.0.4 on 2022-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_permissiontag_options_group_invite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='nickname',
            field=models.CharField(default='', max_length=30, verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
