# Generated by Django 4.0.4 on 2022-05-09 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(db_index=True, related_name='belonged_groups', to=settings.AUTH_USER_MODEL, verbose_name='멤버 목록'),
        ),
    ]
