# Generated by Django 4.0.4 on 2022-05-10 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_systemuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='member_info',
        ),
        migrations.AddField(
            model_name='block',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blocks_in_group', to='users.group', verbose_name='대상 그룹'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL, verbose_name='대상 멤버'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissiontag',
            name='members',
            field=models.ManyToManyField(null=True, related_name='given_permission_tags', to=settings.AUTH_USER_MODEL, verbose_name='대상 멤버'),
        ),
        migrations.DeleteModel(
            name='MemberInfo',
        ),
    ]
