# Generated by Django 4.0.4 on 2022-05-12 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_permissiontag_unique permission tag in group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('body', models.TextField(blank=True, verbose_name='내용')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_terms', to='users.group', verbose_name='대상 그룹')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('term_body', models.TextField(blank=True, null=True, verbose_name='약관 본문')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_spaces', to='users.group', verbose_name='소속 그룹')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='using_spaces', to='reservations.term', verbose_name='등록 약관')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promised_term_body', models.TextField(blank=True, null=True, verbose_name='동의 약관 본문')),
                ('dt_from', models.DateTimeField(verbose_name='예약 시작 일시')),
                ('dt_to', models.DateTimeField(verbose_name='예약 해제 일시')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_member', to=settings.AUTH_USER_MODEL, verbose_name='예약자')),
                ('required_permissions', models.ManyToManyField(db_index=True, related_name='requiring_reservations', to='users.permissiontag', verbose_name='요구 권한')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_space', to='reservations.space', verbose_name='대상 공간')),
            ],
        ),
    ]
