# Generated by Django 4.0.4 on 2022-05-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
