# Generated by Django 4.0.4 on 2022-05-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_permissiontag_unique permission tag in group'),
        ('reservations', '0002_term_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='required_permissions',
        ),
        migrations.AddField(
            model_name='space',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='공간 이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='required_permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requiring_reservations', to='users.permissiontag', verbose_name='요구 권한'),
        ),
    ]
