# Generated by Django 4.0.4 on 2022-05-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_space_required_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '예약', 'verbose_name_plural': '예약 목록'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': '공간', 'verbose_name_plural': '공간 목록'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': '약관', 'verbose_name_plural': '약관 목록'},
        ),
        migrations.RemoveField(
            model_name='term',
            name='modified_at',
        ),
    ]
